name: Genera Rebuttal Word

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Customer Name'
        required: true
      subscription_id:
        description: 'Subscription ID'
        required: true
      subscription_creation_date:
        description: 'Subscription Date (DD.MM.YYYY)'
        required: false
        default: 'N/A'
      shipping_order_id:
        description: 'Shipping Order ID'
        required: false
        default: 'N/A'
      tracking_id:
        description: 'Tracking ID'
        required: false
        default: 'N/A'
      shipping_total_value:
        description: 'Shipping Total Value (es. £100.00)'
        required: false
        default: 'N/A'
      disputed_amount:
        description: 'Disputed Amount + Currency (es. 50.50 EUR)'
        required: true
      delivery_date:
        description: 'Full Bulk Delivery Date (DD.MM.YYYY)'
        required: false
        default: 'N/A'
      consecutive_shipment_number:
        description: 'Consecutive Shipment Number (es. 1, 2...)'
        required: false
        default: 'N/A'
      disputed_charge_date:
        description: 'Disputed Charge Date (DD.MM.YYYY)'
        required: false
        default: 'N/A'
      disputed_instalment:
        description: 'Disputed Instalment (es. 2 of 4)'
        required: false
        default: 'N/A'
      chargeback_reason:
        description: 'Chargeback Reason'
        required: false
        default: 'Subscription Cancelled / Recurring Charge'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-docx python-dateutil

      - name: Genera Documento Word
        run: |
          python generate.py \
            "${{ github.event.inputs.customer_name }}" \
            "${{ github.event.inputs.subscription_id }}" \
            "${{ github.event.inputs.subscription_creation_date }}" \
            "${{ github.event.inputs.shipping_order_id }}" \
            "${{ github.event.inputs.tracking_id }}" \
            "${{ github.event.inputs.shipping_total_value }}" \
            "${{ github.event.inputs.disputed_amount }}" \
            "${{ github.event.inputs.delivery_date }}" \
            "${{ github.event.inputs.consecutive_shipment_number }}" \
            "${{ github.event.inputs.disputed_charge_date }}" \
            "${{ github.event.inputs.disputed_instalment }}" \
            "${{ github.event.inputs.chargeback_reason }}"

      - name: Carica il file nei Risultati (Artifacts)
        uses: actions/upload-artifact@v4
        with:
         path: |
            *.docx
            *.txt
